# Generated by Django 5.1.6 on 2025-03-06 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procoyouApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyerrequest',
            old_name='user',
            new_name='user_id',
        ),
    ]
