# Generated by Django 5.1.6 on 2025-03-06 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procoyouApi', '0002_rename_user_buyerrequest_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyerrequest',
            old_name='user_id',
            new_name='user',
        ),
    ]
