# Generated by Django 5.1.6 on 2025-03-06 15:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procoyouApi', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
