# Generated by Django 5.1.6 on 2025-03-04 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procoyouApi', '0004_customuser_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('price', models.CharField(max_length=50)),
                ('property_type', models.CharField(choices=[('Villa', 'Villa'), ('Apartment', 'Apartment'), ('House', 'House')], max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('furniture_status', models.CharField(choices=[('Furnished', 'Furnished'), ('Unfurnished', 'Unfurnished')], max_length=50)),
                ('bhk_type', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=15)),
                ('cctv', models.BooleanField(default=False)),
                ('lift', models.BooleanField(default=False)),
                ('park', models.BooleanField(default=False)),
                ('swimming_pool', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to='property_media/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='procoyouApi.property')),
            ],
        ),
    ]
