# Generated by Django 5.1.6 on 2025-03-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procoyouApi', '0005_property_propertymedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='looking_for',
            field=models.CharField(choices=[('Sell', 'Sell'), ('Rent', 'Rent'), ('PG', 'PG')], default='Sell', max_length=50),
        ),
    ]
