# Generated by Django 5.1.6 on 2025-03-10 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procoyouApi', '0006_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('price', models.CharField(max_length=50)),
                ('property_type', models.CharField(choices=[('Villa', 'Villa'), ('Apartment', 'Apartment'), ('House', 'House')], max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('furniture_status', models.CharField(choices=[('Furnished', 'Furnished'), ('Semi-furnished', 'Semi-furnished'), ('Unfurnished', 'Unfurnished')], max_length=50)),
                ('bhk_type', models.CharField(max_length=50)),
                ('top_amenities', models.TextField(help_text='Comma-separated list of amenities')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='procoyouApi.buyerrequest')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_proposals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to='proposal_media/')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='procoyouApi.proposal')),
            ],
        ),
    ]
