# Generated by Django 5.1.6 on 2025-03-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procoyouApi', '0006_property_looking_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('price', models.CharField(max_length=50)),
                ('property_type', models.CharField(choices=[('Villa', 'Villa'), ('Apartment', 'Apartment'), ('House', 'House')], max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('furniture_status', models.CharField(choices=[('Furnished', 'Furnished'), ('Semi-furnished', 'Semi-furnished'), ('Unfurnished', 'Unfurnished')], max_length=50)),
                ('bhk_type', models.CharField(max_length=50)),
                ('looking_for', models.CharField(choices=[('Buy', 'Buy'), ('Rent', 'Rent'), ('PG', 'PG')], default='Buy', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
